# Generated by Django 3.1.4 on 2021-02-25 19:16

import apps.produtos.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=450, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=200, verbose_name='Tópico')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Obrigatório', max_length=200, verbose_name='Nome')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', stdimage.models.StdImageField(help_text='Obrigatório', upload_to=apps.produtos.models.adicionar_imagem_logo, verbose_name='Imagem do produto')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Imagem do produto',
                'verbose_name_plural': 'Imagens dos produtos',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Não obrigatório', max_length=200, verbose_name='Nome')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('categoria', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Obrigatório', max_length=250, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Obrigatório', max_digits=10, verbose_name='Preço')),
                ('descricao', models.CharField(help_text='Obrigatório', max_length=450, verbose_name='Descrição')),
                ('quantidade', models.IntegerField(help_text='Obrigatório', verbose_name='Quantidade')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='produtos.categoria')),
                ('subCategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.subcategoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
