# Generated by Django 3.1.4 on 2021-01-31 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='produto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='produtos.categoria'),
        ),
    ]
