# Generated by Django 3.1.4 on 2021-02-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitrines', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vitrine',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrines.vitrine'),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='produto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
    ]
