# Generated by Django 3.1.4 on 2021-03-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20210225_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='numero_acessos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='numero_acessos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
