# Generated by Django 3.1.4 on 2021-02-01 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0004_auto_20210130_2145'),
        ('produtos', '0003_produto_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'verbose_name': 'Subcategoria', 'verbose_name_plural': 'Subcategorias'},
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='produtos.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='vitrine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vitrines.vitrine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(help_text='Obrigatório', max_length=450, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Obrigatório', max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(help_text='Obrigatório', verbose_name='Quantidade'),
        ),
    ]
