# Generated by Django 3.1.4 on 2021-03-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20210305_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='quantidade',
        ),
    ]
