# Generated by Django 3.1.4 on 2021-02-10 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20210209_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='subCategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.subcategoria'),
        ),
    ]
