# Generated by Django 3.1.4 on 2021-03-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_avaliacao_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='observacao',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
