# Generated by Django 3.1.4 on 2021-02-11 21:11

import apps.produtos.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_auto_20210211_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.CreateModel(
            name='imagemProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', stdimage.models.StdImageField(help_text='Obrigatório', upload_to=apps.produtos.models.adicionar_imagem_logo, verbose_name='Imagem do produto')),
                ('produto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Imagem do produto',
                'verbose_name_plural': 'Imagens dos produtos',
            },
        ),
    ]
