# Generated by Django 3.1.4 on 2021-02-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_auto_20210131_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
    ]
