# Generated by Django 3.1.4 on 2021-02-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_produto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
    ]
