# Generated by Django 3.1.4 on 2021-02-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_auto_20210211_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemproduto',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
    ]
