# Generated by Django 3.1.4 on 2021-01-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaoSocial', models.CharField(help_text='Obrigatório', max_length=60, verbose_name='Razão social')),
                ('fantasia', models.CharField(help_text='Obrigatório', max_length=60, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(help_text='Obrigatório', max_length=14, verbose_name='CNPJ')),
                ('inscricaoEstadual', models.CharField(blank=True, help_text='Não obrigatório', max_length=50, null=True, verbose_name='Inscrição Estadual')),
                ('inscricaoMunicipal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Municipal')),
            ],
        ),
    ]
