# Generated by Django 3.1.4 on 2021-01-12 01:27

import apps.empresas.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=stdimage.models.StdImageField(null=True, upload_to=apps.empresas.models.adicionar_imagem_logo, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='inscricaoMunicipal',
            field=models.CharField(blank=True, help_text='Não obrigatório', max_length=50, null=True, verbose_name='Inscrição Municipal'),
        ),
    ]
