# Generated by Django 3.1.4 on 2021-01-12 22:57

import apps.empresas.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20210111_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=stdimage.models.StdImageField(help_text='Obrigatório', null=True, upload_to=apps.empresas.models.adicionar_imagem_logo, verbose_name='Logo da empresa'),
        ),
    ]
