# Generated by Django 3.1.4 on 2021-01-15 00:35

import apps.empresas.validadoresForm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20210112_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(help_text='Obrigatório', max_length=18, validators=[apps.empresas.validadoresForm.validar_cnpj], verbose_name='CNPJ'),
        ),
    ]
