# Generated by Django 3.1.4 on 2020-12-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default=1, help_text='Obrigatório', max_length=50, verbose_name='Bairro'),
            preserve_default=False,
        ),
    ]
