# Generated by Django 3.1.4 on 2020-12-31 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20201231_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Endereço', to='usuarios.endereco'),
        ),
    ]
