# Generated by Django 3.1.4 on 2020-12-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20201231_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='cpf',
            field=models.CharField(help_text='Obrigatório', max_length=11, verbose_name='CPF'),
        ),
    ]
