# Generated by Django 3.1.4 on 2021-01-07 03:05

from django.db import migrations
import stdimage.models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20201231_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='foto',
            field=stdimage.models.StdImageField(null=True, upload_to=usuarios.models.adicionar_imagem_perfil, verbose_name='Foto'),
        ),
    ]
