# Generated by Django 3.1.4 on 2021-01-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20210107_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='data_nascimento',
            field=models.DateField(help_text='Obrigatório', null=True, verbose_name='Data de nascimento'),
        ),
    ]
