# Generated by Django 3.1.4 on 2021-01-07 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20210107_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusuario',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='customusuario',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='numeroCelular',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='numeroFixo',
        ),
        migrations.AddField(
            model_name='endereco',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telefone',
            name='numero',
            field=models.CharField(default='', help_text='Obrigatório', max_length=30, verbose_name='Telefone fixo'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='tipo',
            field=models.CharField(default='', help_text='Obrigatório', max_length=7, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, help_text=' Não obrigatório', max_length=50, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.estado'),
        ),
    ]
