# Generated by Django 3.1.4 on 2021-01-10 22:44

from django.db import migrations
import stdimage.models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20210110_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='foto',
            field=stdimage.models.StdImageField(null=True, upload_to=usuarios.models.adicionar_imagem_perfil, verbose_name='Foto de perfil'),
        ),
    ]
