# Generated by Django 3.1.4 on 2021-01-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20210107_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Status'),
        ),
    ]
