# Generated by Django 3.1.4 on 2021-01-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_endereco_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
