# Generated by Django 3.1.4 on 2021-01-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20210112_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereco', 'verbose_name_plural': 'Enderecos'},
        ),
        migrations.AddField(
            model_name='endereco',
            name='padrao',
            field=models.BooleanField(default=False, verbose_name='Padrao'),
        ),
    ]
