# Generated by Django 3.1.4 on 2021-01-15 14:20

import apps.usuarios.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(help_text='Obrigatório', max_length=100, verbose_name='Primeiro nome')),
                ('last_name', models.CharField(help_text='Obrigatório', max_length=100, verbose_name='Último nome')),
                ('email', models.EmailField(help_text='Obrigatório', max_length=254, unique=True, verbose_name='E-mail')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Membro da equipe')),
                ('cpf', models.CharField(help_text='Obrigatório', max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(help_text='Obrigatório', null=True, verbose_name='Data de nascimento')),
                ('foto', stdimage.models.StdImageField(null=True, upload_to=apps.usuarios.models.adicionar_imagem_perfil, verbose_name='Foto')),
                ('empresa', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', apps.usuarios.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Obrigatório', max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Obrigatório', max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=5, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', help_text='Obrigatório', max_length=7, verbose_name='Tipo')),
                ('numero', models.CharField(default='', help_text='Obrigatório', max_length=30, verbose_name='Telefone fixo')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complemento', models.CharField(blank=True, default='', help_text=' Não obrigatório', max_length=50, null=True, verbose_name='Complemento')),
                ('numero', models.CharField(default='S/N', help_text='Obrigatório', max_length=100, verbose_name='Número')),
                ('rua', models.CharField(help_text='Obrigatório', max_length=100, verbose_name='Rua')),
                ('cep', models.CharField(help_text='Obrigatório', max_length=25, verbose_name='CEP')),
                ('bairro', models.CharField(help_text='Obrigatório', max_length=50, verbose_name='Bairro')),
                ('padrao', models.BooleanField(default=False, verbose_name='Padrao')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.estado')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.estado'),
        ),
    ]
