# Generated by Django 3.1.4 on 2021-01-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='padrao',
            field=models.BooleanField(default=False, verbose_name='Padrao'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
