# Generated by Django 3.1.4 on 2021-01-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210117_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ativo?'),
        ),
    ]
