# Generated by Django 3.1.4 on 2021-02-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0002_auto_20210128_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='empresa',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
