# Generated by Django 3.1.4 on 2021-03-08 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0006_auto_20210306_0120'),
        ('vitrines', '0003_vitrine_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorTotal', models.PositiveIntegerField(verbose_name='Valor total')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pedido_Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco', models.PositiveIntegerField(verbose_name='Preco')),
                ('data_criacao', models.DateField(verbose_name='Data de criação')),
                ('data_retirada', models.DateField(verbose_name='Data de entrega')),
                ('status', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrinhos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitrines.vitrine')),
            ],
            options={
                'verbose_name': 'Pedido_Produto',
                'verbose_name_plural': 'Pedidos_Produtos',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ManyToManyField(through='carrinhos.Pedido_Produto', to='produtos.Produto'),
        ),
    ]
