# Generated by Django 3.1.4 on 2021-03-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinhos', '0002_auto_20210309_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valorTotal',
        ),
        migrations.AlterField(
            model_name='pedido_produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Obrigatório', max_digits=10, verbose_name='Preço'),
        ),
    ]
