# Generated by Django 3.1.4 on 2021-03-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinhos', '0003_auto_20210311_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_produto',
            name='precoTotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Obrigatório', max_digits=10, verbose_name='Preço total'),
        ),
    ]
