# Generated by Django 3.1.4 on 2021-03-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinhos', '0004_pedido_produto_precototal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
    ]
