# Generated by Django 3.1.4 on 2021-03-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinhos', '0005_pedido_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido_produto',
            old_name='data_criacao',
            new_name='dataCriacao',
        ),
        migrations.RenameField(
            model_name='pedido_produto',
            old_name='status',
            new_name='statusFinalizado',
        ),
        migrations.RemoveField(
            model_name='pedido_produto',
            name='data_retirada',
        ),
        migrations.AddField(
            model_name='pedido_produto',
            name='dataRetirada',
            field=models.DateField(null=True, verbose_name='Data de entrega'),
        ),
        migrations.AddField(
            model_name='pedido_produto',
            name='statusReservado',
            field=models.BooleanField(default=False, verbose_name='Reservado'),
        ),
    ]
