# Generated by Django 3.1.4 on 2021-03-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinhos', '0006_auto_20210312_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='status',
            new_name='statusFinalizado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='statusReservado',
            field=models.BooleanField(default=False, verbose_name='Reservado'),
        ),
    ]
