# Generated by Django 3.1.4 on 2021-01-20 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitrine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Obrigatório', max_length=60, verbose_name='Nome')),
                ('descricao', models.CharField(help_text='Obrigatório', max_length=200, verbose_name='Descrição')),
                ('vendedor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vitrine',
                'verbose_name_plural': 'Vitrines',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=0, verbose_name='Nota')),
                ('observacao', models.TextField(help_text='Não obrigatório', max_length=250, null=True, verbose_name='Observação')),
                ('cliente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vitrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrines.vitrine')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
    ]
