# Generated by Django 3.1.4 on 2021-03-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrines', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
