# Generated by Django 3.1.4 on 2021-03-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('vitrines', '0002_delete_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrine',
            name='empresa',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
