# Generated by Django 3.1.4 on 2021-01-31 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('vitrines', '0002_vitrine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='produtos.produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='vitrine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitrines.vitrine'),
        ),
        migrations.AlterField(
            model_name='vitrine',
            name='descricao',
            field=models.CharField(help_text='Obrigatório', max_length=450, verbose_name='Descrição'),
        ),
    ]
