# Generated by Django 3.1.4 on 2021-03-15 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('vitrines', '0003_vitrine_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitrine',
            name='empresa',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
        ),
    ]
