# Generated by Django 3.1.4 on 2021-01-31 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20210130_2145'),
        ('vitrines', '0003_auto_20210130_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='produto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='vitrine',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='vitrines.vitrine'),
        ),
    ]
